#!/bin/bash

#Saves input 1
#Starts on cross in start button window
#pixel 503 519 here

xdotool mousemove 503 519 click 1 sleep 1 mousemove_relative -- 305 -220 sleep 1 click 1 sleep 1 key Tab sleep 0.5 key Return sleep 1 mousemove 503 519 key Ctrl+Alt+g
